name: Run unittests for OTUServer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run linter Flake8
      run: |
        flake8 --exclude tests -v
#    - uses: actions/checkout@v3
#      with:
#        submodules: recursive
    - name: Clone tests
      run: git clone https://github.com/s-stupnikov/http-test-suite.git tests
    - name: Buld docker image
      run: docker build -t myapp .
    - name: Run server image
      run: docker run -d -p 80:80 myapp
    - name: Run Tests with coverage
      run: |
        python3 -m coverage run -m unittest -v tests/httptest.py
        python3 -m coverage report